### PR TITLE
Option to disable auto open of browser

### PR DESCRIPTION
**Pull request by ammerritt**

### CODE REVIEW

**Comment by JamieCrisman** [comment]
:+1:
is there a way we can send an argument to gulp to not open it as well?

something like:

``` sh
gulp pleaseStopOpeningNewTabs
```

**Comment by robmcguinness** [comment]
@JamieCrisman this should be the same thing

**Comment by ammerritt** [comment]
@JamieCrisman  you can.  I have put in another pull request here that adds a 
--pleaseStopOpeningNewTabs option you can pass to gulp to override even what was set in the config. https://github.com/ammerritt/availity-toolkit/pull/1/files

**Comment by robmcguinness** [comment]
this PR was addressed in #16

**Pull request closed without merging**
